// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdhitkznmwltslilihxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaGl0a3pubXdsdHNsaWxpaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTQzNjYsImV4cCI6MjA2MjU5MDM2Nn0.o_fZ0FTqO2hKeliBhGcY7ZXJfrrClX33SAPkLkRGdCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);